name: mle-editor
summary: Flexible terminal-based editor.
description: |
  mle is a small, flexible, terminal-based text editor written in C. 
  Notable features include: full Unicode support, syntax highlighting, 
  scriptable rc file, macros, search and replace (PCRE), window 
  splitting, multiple cursors, and integration with various shell 
  commands.
version: 1.5.0
license: Apache-2.0
base: core22
grade: stable
confinement: strict

apps:
  mle:
    command: usr/local/bin/mle

parts:
  mle:
    plugin: make
    source: https://github.com/adsr/mle.git
    source-commit: 466febb604027149a341a3c75a7fb8b386b942fa
    source-type: git
    make-parameters: ["mle_vendor=1", "mle_static=1"]
    build-environment:
    - SNAPCRAFT_PARALLEL_BUILD_COUNT: "1"
    build-packages: [libtool, automake]
    stage-packages: [fzf, tree, less, perl, universal-ctags]
