name: mle-editor
summary: Flexible terminal-based editor.
description: |
  mle is a small, flexible, terminal-based text editor written in C. 
  Notable features include: full Unicode support, syntax highlighting, 
  scriptable rc file, macros, search and replace (PCRE), window 
  splitting, multiple cursors, and integration with various shell 
  commands.
version: 1.7.2
license: Apache-2.0
base: core22
grade: stable
confinement: strict

apps:
  mle:
    command: usr/local/bin/mle

parts:
  mle:
    plugin: make
    source: https://github.com/adsr/mle.git
    source-commit: 064147fc83e5587bf793cb8ccbfe51525c6b5489
    source-type: git
    make-parameters: ["-j1", "mle_vendor=1", "mle_static=1"]
    build-packages: [libtool, automake]
    stage-packages: [fzf, tree, less, perl, universal-ctags]
